Suggest adding `no_main` for `error[E0601]` (#1113)
* Use duct to build/invoke cargo command

* Push command to args

* Ignore cargo tree stdout

* Suggest adding `no_main`

* Read one byte at a time to get the progress bar

* Refactor to separate method

* Update crates/build/src/lib.rs

Co-authored-by: Michael Müller <mich@elmueller.net>

* Detect term size

* Update suggestion and exit on error

* Update message

* Hardcode term size

* Hardcode term size

* Only detect term size on non windows OS

* Red

* Use term_size for windows

* use term_size as _;

---------

Co-authored-by: Michael Müller <mich@elmueller.net>